export const OPERATION_DESCRIPTIONS = {
  EML:     "exp(x) \u2212 ln(y)",
  "1":     "constant: 1",
  "0":     "constant: 0",
  "-1":    "constant: \u22121",
  "2":     "constant: 2",
  x:       "variable",
  y:       "variable",
  z:       "variable",
  e:       "Euler's number \u2248 2.718",
  pi:      "\u03c0 \u2248 3.14159",
  sin:     "sine",
  cos:     "cosine",
  tan:     "tangent",
  asin:    "inverse sine",
  acos:    "inverse cosine",
  atan:    "inverse tangent",
  sinh:    "hyperbolic sine",
  cosh:    "hyperbolic cosine",
  tanh:    "hyperbolic tangent",
  asinh:   "inverse hyperbolic sine",
  acosh:   "inverse hyperbolic cosine",
  atanh:   "inverse hyperbolic tangent",
  sqrt:    "square root: \u221ax",
  exp:     "exponential: e\u02e3",
  log:     "natural logarithm",
  half:    "x / 2",
  inv:     "1 / x",
  sqr:     "x\u00b2",
  sigma:   "logistic sigmoid: 1/(1+e\u207b\u02e3)",
  avg:     "(x + y) / 2",
  hypot:   "\u221a(x\u00b2 + y\u00b2)",
}
